packages:
  - apps/*
  - packages/*

catalog:
  '@base-ui/react': 1.2.0
  '@eslint/js': 10.0.1
  '@fastify/cookie': 11.0.2
  '@nestjs/bullmq': 11.0.4
  '@nestjs/cli': 11.0.16
  '@nestjs/common': 11.1.13
  '@nestjs/config': 4.0.3
  '@nestjs/core': 11.1.13
  '@nestjs/event-emitter': 3.0.1
  '@nestjs/jwt': 11.0.2
  '@nestjs/platform-fastify': 11.1.13
  '@nestjs/testing': 11.1.13
  '@tailwindcss/vite': 4.1.18
  '@types/node': 24.1.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react-swc': 4.2.3
  axios: 1.13.5
  bcryptjs: 3.0.3
  bullmq: 5.69.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  drizzle-kit: 0.31.9
  drizzle-orm: 0.45.1
  embla-carousel-react: 8.6.0
  eslint: 10.0.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.5
  eslint-plugin-react-hooks: 7.0.1
  fastify: 5.7.4
  framer-motion: 12.34.0
  globals: 17.3.0
  input-otp: 1.4.2
  ioredis: 5.9.3
  lucide-react: 0.563.0
  nestjs-pino: 4.5.0
  next-themes: 0.4.6
  pino: 10.3.1
  pino-http: 11.0.0
  pino-pretty: 13.1.3
  postgres: 3.4.8
  prettier: 3.8.1
  radix-ui: 1.4.3
  react: 19.2.4
  react-day-picker: 9.13.2
  react-dom: 19.2.4
  react-error-boundary: 6.1.0
  react-hook-form: 7.71.1
  react-resizable-panels: 4.6.2
  react-router: 7.13.0
  recharts: 2.15.3
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  sonner: 2.0.7
  swr: 2.4.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tsdown: 0.20.3
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  typescript-eslint: 8.55.0
  vaul: 1.1.2
  vite: 7.3.1
  vitest: 4.0.18
  '@vitest/coverage-v8': 4.0.18
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.2.0
  '@testing-library/user-event': 14.6.1
  jsdom: 26.1.0
  msw: 2.12.10
  zod: 4.3.6
  zustand: 5.0.11
  i18next: 25.8.7
  react-i18next: 16.5.4
  i18next-browser-languagedetector: 8.2.1
  nestjs-i18n: 10.6.0
  i18next-parser: 9.3.0
  '@playwright/test': 1.52.0
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  husky: 9.1.7
  release-it: 19.0.4
  git-cliff: 2.12.0
