import type { OrganizationUserRole } from '../schemas/organization.schema';
import type { Permission } from './list';


/**
 * Role to permissions mapping.
 * Each role has an explicit list of permissions - no inheritance.
 */
export const ROLE_PERMISSIONS: Record<OrganizationUserRole, readonly Permission[]> = {
  OWNER: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:update',
    'org:switch',
    'user:list',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'user:create-owner',
    'user:promote-owner',
    'user:remove-owner',
    'job:create',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
    'settings:update',
  ],
  ADMIN: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:switch',
    'user:list',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'job:create',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
    'settings:update',
  ],
  MEMBER: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:switch',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
  ],
} as const;
