/// <reference types="nativewind/types" />

// NOTE: This file is (re)generated by react-native-css when Metro runs; it
// wires up `className` typings on React Native components. Committed so
// typecheck passes without a Metro run.
